require "vmarmin.options"       -- lua/vmarmin/options.lua
require "vmarmin.keymaps"       -- lua/vmarmin/keymaps.lua
require "vmarmin.plugins"       -- lua/vmarmin/plugins.lua
require "vmarmin.colorscheme"   -- lua/vmarmin/colorscheme.lua
require "vmarmin.nvimtree"      -- lua/vmarmin/nvimtree.lua
require "vmarmin.signify"       -- lua/vmarmin/signify.lua
require "vmarmin.lualine"       -- lua/vmarmin/lualine.lua
require "vmarmin.commentary"    -- lua/vmarmin/commentary.lua
require "vmarmin.fugitive"      -- lua/vmarmin/fugitive.lua
require "vmarmin.telescope"     -- lua/vmarmin/telescope.lua
